spring.application.name=proyecto-integrador


spring.datasource.url=jdbc:mysql://localhost:3306/clinic_db2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate: genera las tablas a partir de las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT settings
security.jwt.secret=ZmFrZV9zZWNyZXRfZm9yX2RldmVsb3BtZW50XzY0Ynl0ZXM=
security.jwt.expirationMillis=300000